

export const dataTV = [
    {
        id: 1,
        name: "Big Bang Theory",
        rate: "⭐⭐⭐⭐⭐",
        image: "https://cdn.europosters.eu/image/1300/art-photo/the-big-bang-theory-crew-i106240.jpg" ,
        genre: "Comedy",
        number_of_seasons: 12,
        year: "2007-2019",
        director: "Mark Cendrowski",
        plot: `The Big Bang Theory is a comedy about brilliant physicists, Leonard and Sheldon, who are the kind of "beautiful minds" that understand how the universe works. But none of that genius helps them interact with people, especially women. All this begins to change when a free-spirited beauty named Penny moves in next door.`,
        showMore: false
    },

   { id: 2,
    name: "Big Little lies",
    rate: "⭐⭐⭐⭐",
    image: "https://m.media-amazon.com/images/M/MV5BNDc2MDE3NzkyNF5BMl5BanBnXkFtZTgwOTI0ODAxMTI@._V1_FMjpg_UX1000_.jpg",
    genre: "Drama",
    number_of_seasons: 2,
    year: "2017-2019",
    director: "Jean-Marc Vallée Andrea Arnold",
    plot: `A darkly comedic tale of murder and mischief in the tranquil beachfront town of Monterey, Calif. Amidst doting moms, successful husbands, beautiful children, and stunning homes exists a community fueled by rumors and divided into haves and have-nots, exposing fractured relationships between husbands and wives, parents and children, and friends and neighbors. Told through the eyes of three mothers -- Madeline, Celeste and Jane -- the series' narrative explores society's myths regarding perfection and its romanticization of marriage, sex, parenting and friendship.`,
    showMore: false
},
{ id: 3,
    name: "Emily in Paris",
    rate: "⭐⭐⭐⭐",
    image: "https://tv-fanatic-res.cloudinary.com/iu/s--TZps7AUM--/f_auto,q_auto/v1598973306/emily-in-paris-poster",
    genre: "Drama Comedy",
    number_of_seasons: 2,
    year: "2020-present",
    director: "Andrew Fleming",
    plot: `Emily in Paris follows Emily Cooper, a college graduate American with a Master's degree in marketing in her late twenties from Chicago, who moves to Paris for an unexpected job opportunity. She is tasked with bringing an American point of view to a venerable French marketing firm.`,
    showMore: false
},
{ id: 4,
    name: "Game of throne",
    rate: "⭐⭐⭐⭐⭐",
    image: "https://cdn11.bigcommerce.com/s-b72t4x/images/stencil/1280x1280/products/24556/33921/PP32783__82409.1624831032.jpg",
    genre: "Drama Action Fantasy",
    number_of_seasons: 8,
    year: "2011-2019",
    director: " Alex Graves, David Nutter",
    plot: `The show is divided into three major plot lines. The first covers the battle between the lords of the continent of Westeros — most notably members of the Baratheon, Lannister, and Stark families — who are involved in the fight for the Iron Throne. The second follows the rise of Daenerys Targaryen, the last member of an exiled family as she builds an army in Essos to reclaim the throne. The third plot takes place in the North of Westeros among the Night's Watch, an armed unit that guards the 300-mile-long, 70-foot-tall wall that protects the rest of the continent from the mythical creatures that lurk there.`,
    showMore: false
},
{ id: 5,
    name: "How I met your mother",
    rate: "⭐⭐⭐⭐⭐",
    image: "https://cdn.shopify.com/s/files/1/0969/9128/products/HowIMetYourMother-ClassicTVShowPoster6_37669e1e-0010-4499-961d-84357f60ee14.jpg?v=1596545753",
    genre: "Comedy",
    number_of_seasons: 9,
    year: "2005-2014",
    director: " Pamela Fryman",
    plot: `The series revolves around Ted Mosby (Josh Radnor) who in the year of 2030 tells the story to his son and daughter how he met their mother (hence the title). While living in New York City and working as an architect, the narrative deals with his best friends, including the long-lasting couple Marshall Eriksen (Jason Segel) and Lily Aldrin (Alyson Hannigan); the eccentric, womanizer-playboy Barney Stinson (Neil Patrick Harris); and news anchor Robin Scherbatsky (Cobie Smulders). The series explores many storylines, including a love triangle between Robin, Ted, and Barney; Marshall and Lily's relationship; as well as the careers of the characters and so much more. The series is narrated by Bob Saget through flashbacks from the future.`,
    showMore: false
},
{ id: 6,
    name: "Maid",
    rate: "⭐⭐⭐⭐⭐",
    image: "https://media.kg-portal.ru/tv/m/maid/posters/maid_1.jpg",
    genre: "Drama",
    number_of_seasons: 1,
    year: "2021",
    director: "John Wells",
    plot: `The series is inspired by Stephanie Land's memoir Maid: Hard Work, Low Pay, and a Mother's Will to Survive. Its story focuses on a young mother who escapes an abusive relationship, subsequently struggling to provide for her daughter by getting a job cleaning houses.`,
    showMore: false
},
{ id: 7,
    name: "Sex education",
    rate: "⭐⭐⭐⭐⭐",
    image: "https://www.tvguide.com/a/img/catalog/provider/1/1/1-6955305959.jpg",
    genre: "Drama Comedy",
    number_of_seasons: 3,
    year: "2019-present",
    director: "Ben Taylor",
    plot: `"Socially awkward high school student Otis may not have much experience in the lovemaking department, but he gets good guidance on the topic in his personal sex ed course -- living with mom Jean, who is a sex therapist. Being surrounded by manuals, videos and tediously open conversations about sex, Otis has become a reluctant expert on the subject. When his classmates learn about his home life, Otis decides to use his insider knowledge to improve his status at school, so he teams with whip-smart bad girl Maeve to set up an underground sex therapy clinic to deal with their classmates' problems. But through his analysis of teenage sexuality, Otis realizes that he may need some therapy of his own.`,
    showMore: false
},
{ id: 8,
    name: "Sherlock",
    rate: "⭐⭐⭐⭐⭐",
    image: "https://static.insales-cdn.com/images/products/1/3688/205327976/59ec2e5de8021f16fa608d982e5abc27bd67fd06.jpg",
    genre: "Detective Drama",
    number_of_seasons: 4,
    year: "2010-2017",
    director: "Paul McGuigan",
    plot: `Sherlock Holmes lives in 21st-century London, a city filled with mystery, crime, and deceit. The back streets are alive with robbers, blackmailers, smugglers, and serial killers. When the police are desperate they call upon Mr Sherlock Holmes and his unconventional methods of deduction to shed light on the matter.`,
    showMore: false
},
{ id: 9,
    name: "Stranger things",
    rate: "⭐⭐⭐⭐⭐",
    image: "https://i.ebayimg.com/images/g/WFsAAOSw3~RijpbL/s-l1600.jpg",
    genre: "Fantasy Thriller",
    number_of_seasons: 4,
    year: "2016-present",
    director: "Matt Duffer & Ross Duffer",
    plot: `When Will Byers suddenly goes missing, the whole town of Hawkins, Indiana, turns upside down. Many people are on the search for Will, including his mother Joyce, his brother Jonathan, his friends Mike, Dustin, and Lucas, Police Chief Jim Hopper, and other notable people. But one thing leads to another, creating a supernatural trail. And things get even weirder when a little girl with a shaved head comes into the story.`,
    showMore: false
},
{ id: 10,
    name: "Ted Lasso",
    rate: "⭐⭐⭐⭐⭐",
    image: "https://www.film.ru/sites/default/files/movies/posters/49552460-1653861.jpg",
    genre: "Comedy Drama",
    number_of_seasons: 2,
    year: "2020-present",
    director: "Philip Sgriccia",
    plot: `The series follows Ted Lasso, an American college football coach who is hired to coach an English soccer team in an attempt by its owner to spite her ex-husband. Lasso tries to win over the skeptical English market with his folksy, optimistic demeanor while dealing with his inexperience in the sport.`,
    showMore: false
},
{ id: 11,
    name: "The boys",
    rate: "⭐⭐⭐⭐⭐",
    image: "https://static.insales-cdn.com/images/products/1/3532/422612428/iiaWaSW9Fdk.jpg",
    genre: "Comedy Drama Fantasy Action",
    number_of_seasons: 3,
    year: "2019-present",
    director: "Eric Kripke",
    plot: `The Boys is set in a universe in which superpowered people are recognized as heroes by the general public and owned by a powerful corporation, Vought International, which ensures that they are aggressively marketed and monetized. Outside of their heroic personas, most are arrogant and corrupt.`,
    showMore: false
},
{ id: 12,
    name: "The office",
    rate: "⭐⭐⭐⭐⭐",
    image: "https://www.film.ru/sites/default/files/movies/posters/1632214-902735.jpg",
    genre: "Comedy",
    number_of_seasons: 9,
    year: "2005-2013",
    director: "Randall Einhorn",
    plot: `A series about the workdays of a small regional office of a large company, the inhabitants of which must endure the kookies of their unlucky boss all day long.`,
    showMore: false
}
]